# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03b971198175e7ade1d54e3f8fcdba8b012f19b70148385d78ec432a498a04e7cad3a5629580671e497083ca9044ca4e61908afbd57b92769b1caa8309b9b6d

test:
  secret_key_base: a08f54390de787f5b5a23548627c338e4932ba4305b4644f62c31037e5f2d38a3d7c165ce07dfb609e218be89add12f34e729961e720aa8d33c3213210f0c324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
